### ISSUE TITLE
Developed for python3 but when is installed with pip is not forced to use python 3

### ISSUE THREAD

**Issue by jfestrada** [huwwp/cryptop#18]
Hi, 

I've installed it using "sudo pip install cryptop" but when I try to run it I got the following issue:

Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 9, in <module>
    load_entry_point('cryptop==0.1.2', 'console_scripts', 'cryptop')()
  File "/usr/local/lib/python2.7/dist-packages/cryptop.py", line 202, in main
    os.makedirs(basedir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

So I've investigated a little bit and I found that exist_ok is only for python >= 3.2 and in my machine was running under python 2.7 after be installed with pip.

**Comment by huwwp** [comment]
Added to the readme you may need to install with pip3 depending on your python install
