### ISSUE TITLE
config.ini is missing when is installed with pip

### ISSUE THREAD

**Issue by jfestrada** [huwwp/cryptop#20]
Hi, 

When cryptop is installed with pip the config.ini is missing and have to be created manually.

Br

**Comment by jgoggan** [comment]
I had this same problem under Windows.  (In fact, I still can't get it to work because even with a copied-in config.ini, I am getting errors from configparser.py.)  I'll post more if I get it figured out.

**Comment by jgoggan** [comment]
Ok -- got this to work under Windows GitHub Bash.  As was said, it did not do an initial config.ini for some reason.  While I had the one grabbed via Git, I didn't have a custom one.  When I looked in ~/.cryptop, there was an EMPTY config.ini there.  I replaced it with the default -- and now cryptop runs fine.  Thanks!

**Comment by huwwp** [comment]
My mistake, need to add it to the manifest.in or setup.py package_data. I'll push out a fix soon

**Comment by huwwp** [comment]
This should be resolved, let me know if you are still having issues
