### ISSUE TITLE
Columns shifted if held field too large

### ISSUE THREAD

**Issue by jgoggan** [huwwp/cryptop#24]
If you have a HELD amount bigger than 4 digits to the left of the decimal, then the entire column gets shifted to the right (as well as the rest of the columns to the right).  It would be good if we could expand the column sizes (or even auto-adjust them all if one is too large).

Not usually an issue with BTC -- if someone has 10000+, then they likely aren't worried about tracking it here.  But, for those of us Shibes with Dogecoin, it isn't a big deal to have 5-digit or even 6-digit coins held.  (100,000 Dogecoin is like $170.)

Thanks!

**Comment by huwwp** [comment]
The lastest build includes options in the ini to set max field width, and it trims off decimal places if it exceeds this. You can copy the fields from the config.ini in the repo or delete the old one and it will be make a new one with the new options present.

**Comment by jgoggan** [comment]
This is perfect now.  Thanks!

**Comment by nrenich** [comment]
This is very nice.
