### ISSUE TITLE
Sort Options?

### ISSUE THREAD

**Issue by nrenich** [huwwp/cryptop#31]
Just some feedback, love what you are doing with this tool so far. It would be nice if there was some way to sort the output. Maybe by coin, price, or val? Or maybe display them in order as saved in the wallet.dat file.

**Comment by huwwp** [comment]
Most recent thing I added to the todo.txt! Should be in the next feature update

**Comment by huwwp** [comment]
Introduced ascending/descending sorting on amount held. Still considering value sort

**Comment by nrenich** [comment]
Great job, thanks. This helps my OCD. :)

**Comment by huwwp** [comment]
Latest build has value sorting too
