### ISSUE TITLE
Coin data only saved at exit?

### ISSUE THREAD

**Issue by jgoggan** [huwwp/cryptop#32]
It appears that your coin data is only saved at exit.  Unfortunately, now and then it crashes on me.  Or, for various reasons, I happen to kill the shell it is running in or something.  When that happens, any adjustments to coin values that I made are lost.

Wouldn't it be wise to save the coin data after each coin addition, update, or removal -- instead of just at exit?  Just thought that would make good sense to throw a save in there each time you update.

Thanks!

**Comment by huwwp** [comment]
Yeah that makes way more sense, I'll test performance and push it in the next update.

**Comment by huwwp** [comment]
Latest build writes to wallet on each addition or removal
